# Generated by Django 2.0.7 on 2020-10-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_information',
            fields=[
                ('customer_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=30)),
                ('email_id', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
