# Generated by Django 2.0.7 on 2020-10-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_information',
            name='email_id',
            field=models.CharField(max_length=40),
        ),
    ]
