# Generated by Django 2.0.7 on 2020-10-31 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201031_2108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer_information',
        ),
    ]
