# Generated by Django 2.0.7 on 2020-10-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_customer_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_information',
            name='customer_name',
            field=models.CharField(max_length=40),
        ),
    ]
