# Generated by Django 2.0.7 on 2020-11-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201031_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='painting_information',
            fields=[
                ('painting_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=40)),
                ('painting_name', models.CharField(max_length=60)),
            ],
        ),
    ]
