# Generated by Django 2.0.7 on 2020-11-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_painting_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_information',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customer_information',
            name='customer_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Customer ID'),
        ),
        migrations.AlterField(
            model_name='customer_information',
            name='customer_name',
            field=models.CharField(max_length=40, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='customer_information',
            name='email_id',
            field=models.CharField(max_length=40, verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='painting_information',
            name='artist_name',
            field=models.CharField(max_length=40, verbose_name='Artist Name'),
        ),
        migrations.AlterField(
            model_name='painting_information',
            name='painting_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Painting ID'),
        ),
        migrations.AlterField(
            model_name='painting_information',
            name='painting_name',
            field=models.CharField(max_length=60, verbose_name='Painting Name'),
        ),
    ]
