# Generated by Django 2.0.7 on 2020-11-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20201101_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer_information',
            options={'verbose_name': 'Customer Information', 'verbose_name_plural': 'Customer Information'},
        ),
        migrations.AlterModelOptions(
            name='painting_information',
            options={'verbose_name': 'Painting Information', 'verbose_name_plural': 'Painting_Information'},
        ),
    ]
