# Generated by Django 2.0.7 on 2020-11-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20201102_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_information',
            name='issue_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='sales_information',
            name='return_date',
            field=models.DateField(default=None),
        ),
    ]
