# Generated by Django 2.0.7 on 2020-11-05 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20201104_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales_information',
            options={'verbose_name': 'Sales Information', 'verbose_name_plural': 'Sales Information'},
        ),
    ]
