# Generated by Django 2.0.7 on 2020-11-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20201105_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_information',
            name='photo',
            field=models.ImageField(default=None, upload_to='media'),
        ),
    ]
