# Generated by Django 3.0.11 on 2020-11-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_sales_information_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_information',
            name='photo',
        ),
        migrations.AddField(
            model_name='painting_information',
            name='photo',
            field=models.ImageField(default=None, upload_to='media'),
        ),
    ]
