# Generated by Django 3.0.11 on 2020-11-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20201110_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting_information',
            name='price',
            field=models.IntegerField(default=None),
        ),
    ]
