# Generated by Django 3.0.11 on 2020-11-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_painting_information_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting_information',
            name='photo',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
    ]
