# Generated by Django 3.0.11 on 2020-11-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20201116_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting_information',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
