# Generated by Django 3.0.11 on 2020-11-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_painting_information_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting_information',
            name='slug',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
