# Generated by Django 3.0.11 on 2020-11-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_painting_information_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='painting_information',
            unique_together={('painting_id', 'slug')},
        ),
    ]
