# Generated by Django 3.0.11 on 2020-11-19 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0022_auto_20201116_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_information',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customer_information',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customer_information',
            name='email_id',
        ),
        migrations.AddField(
            model_name='customer_information',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer_information',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
