# Generated by Django 3.0.11 on 2020-11-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_20201119_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_information',
            old_name='customer_id',
            new_name='user',
        ),
    ]
