# Generated by Django 3.0.11 on 2020-11-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20201119_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_information',
            name='phno',
            field=models.CharField(default=None, max_length=10, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
