# Generated by Django 3.0.11 on 2020-11-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_customer_information_phno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales_information',
            options={},
        ),
        migrations.RemoveField(
            model_name='sales_information',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='sales_information',
            name='painting_id',
        ),
        migrations.RemoveField(
            model_name='sales_information',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='sales_information',
            name='user',
        ),
        migrations.AddField(
            model_name='sales_information',
            name='sale',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
