# Generated by Django 3.0.11 on 2020-11-19 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_auto_20201119_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales_information',
            options={'verbose_name': 'Sales Information', 'verbose_name_plural': 'Sales Information'},
        ),
        migrations.RemoveField(
            model_name='sales_information',
            name='sale',
        ),
        migrations.AddField(
            model_name='sales_information',
            name='customer_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.customer_information'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales_information',
            name='issue_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='sales_information',
            name='painting_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.painting_information'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales_information',
            name='return_date',
            field=models.DateField(default=None),
        ),
    ]
