# Generated by Django 3.0.11 on 2020-11-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_auto_20201119_1804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sales_information',
        ),
    ]
