# Generated by Django 3.0.11 on 2020-11-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_delete_sales_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting_information',
            name='description',
            field=models.CharField(default=None, max_length=10000),
        ),
    ]
