# Generated by Django 3.0.11 on 2020-11-19 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_painting_information_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='tiers',
            fields=[
                ('tier', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('discount', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='tiers_customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tiers')),
            ],
        ),
        migrations.DeleteModel(
            name='customer_information',
        ),
    ]
