# Generated by Django 3.0.11 on 2020-11-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_auto_20201119_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiers',
            options={'verbose_name': 'Tier', 'verbose_name_plural': 'Tiers'},
        ),
    ]
