# Generated by Django 3.0.11 on 2020-11-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_tiers_customer_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tiers_customer',
        ),
    ]
