# Generated by Django 3.0.11 on 2020-11-19 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_order_information_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='warehouse_paintings',
        ),
        migrations.AddField(
            model_name='painting_information',
            name='wrhouse',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.warehouse'),
        ),
    ]
