# Generated by Django 3.0.11 on 2020-11-19 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_auto_20201120_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting_information',
            name='wrhouse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.warehouse'),
        ),
    ]
