# Generated by Django 3.0.11 on 2020-11-19 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_auto_20201120_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting_information',
            name='wrhouse',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_paintings',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.painting_information', verbose_name='Paintings'),
            preserve_default=False,
        ),
    ]
