# Generated by Django 3.0.11 on 2020-11-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0039_auto_20201120_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='warehouse_paintings',
        ),
    ]
