# Generated by Django 3.0.11 on 2020-11-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0040_remove_warehouse_warehouse_paintings'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_id',
            field=models.CharField(max_length=20, verbose_name='Warehouse ID'),
        ),
    ]
