# Generated by Django 3.0.11 on 2020-11-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_auto_20201120_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='id',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Warehouse ID'),
        ),
    ]
