# Generated by Django 3.0.11 on 2020-11-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0042_auto_20201120_0141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='warehouse',
        ),
    ]
