# Generated by Django 3.0.11 on 2020-11-19 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0043_delete_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_id', models.CharField(max_length=20, verbose_name='Warehouse ID')),
                ('warehouse_name', models.CharField(max_length=50, verbose_name='Warehouse Name')),
            ],
        ),
        migrations.AddField(
            model_name='painting_information',
            name='wr_house',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.warehouse'),
            preserve_default=False,
        ),
    ]
