# Generated by Django 3.0.11 on 2020-11-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0044_auto_20201120_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting_information',
            name='wr_house',
        ),
    ]
