# Generated by Django 3.0.11 on 2020-11-19 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0045_remove_painting_information_wr_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='warehouse_painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.painting_information')),
                ('ware', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.warehouse')),
            ],
        ),
    ]
